vich_uploader:
    db_driver: orm

    mappings:
        user_img:
            uri_prefix: /assets/imgs/profile
            upload_destination: '%kernel.project_dir%/public/assets/imgs/profile'
            namer:
              service: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true