vich_uploader:
    db_driver: orm

    mappings:
        user_img:
            uri_prefix: /assets/imgs/profile
            upload_destination: '%kernel.project_dir%/public/assets/imgs/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer